### ISSUE TITLE
n_samples size is equal to zero.

### ISSUE THREAD

**Issue by KartikayKumar02** [VikramShenoy97/Music-Recommendation-Using-Deep-Learning#2]
When executing the script train.py , it gives an error stating that n_samples=0. I think the issue here is either in the create_spectrogram fucntion or either in load_data script. Could you shed more light on this issue ?

**Comment by KartikayKumar02** [comment]
Found the problem in import_Data file. The line 
"track_id = int(re.search('fma_small/.*/(.+?).mp3', f).group(1))"
 is returning nothing so the group function raises an attribute error therefore the mp3 files are never converted to spectrograms and thus n_samples=0. Please fix the regular expression.

**Comment by yatri1609** [comment]
@gaggs Did you find a way to make it work?

**Comment by KartikayKumar02** [comment]
No I couldn't as the code is deprecated. I had to write most of it from scratch.

**Comment by yatri1609** [comment]
Ohh ohk

**Comment by VikramShenoy97** [comment]
Hi, Sorry for the delay in responding. I'm currently working on upgrading the code to Python3 as well as trying out different architectures based on current research. This will take some time since I'm currently working on my Internship and will be pre-occupied till September. That being said, I ran a quick experimental check on the python3 script for the same code and I only faced an issue with pandas (related to encodings, the issue has been resolved) and the python3 script seems to be generating the spectrograms as expected. I did not come across any issue with the n_samples being equal to 0 or the regular expression causing an error. So based on my findings, I would suggest redownloading the dataset or making sure the csv file isn't corrupted. While working on this project in the initial phases, I found it hard to download the dataset and was quite often getting corrupted files due to the sheer size of the dataset and errors in download. Hope this helps! I'll try responding to this thread once the new code is out. Good luck!
